name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t blogapp:latest .

      - name: Archive Docker image
        run: |
          docker save blogapp:latest | gzip > blogapp.tar.gz

      - name: Deploy Docker image to EC2
        run: |
          scp blogapp.tar.gz user@ec2-instance:/path/to/app
          ssh user@ec2-instance "\
            cd /path/to/app && \
            gunzip -c blogapp.tar.gz | docker load && \
            docker stop blogapp || true && \
            docker run -d -p 3000:3000 --name blogapp blogapp:latest"
